# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings
# - name: WhitespaceTokenizer
#   - name: CRFEntityExtractor
#   - name: EntitySynonymMapper
#   - name: CountVectorsFeaturizer
#     token_pattern: (?u)\b\w+\b
#   - name: EmbeddingIntentClassifier
#   - name: DucklingHTTPExtractor
#     url: http://localhost:8000
#     dimensions:
#       - number

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: FormPolicy
  - name: MappingPolicy
